//! End-to-end escrow lifecycle (Issue #292).
//!
//! Deploys the escrow contract into a mock Soroban [`Env`] — alongside the
//! registry and treasury it interacts with — and drives the full escrow
//! lifecycle across the release, refund and cancel paths:
//!
//! 1. **Happy path**: create → release → close, with balances checked at
//!    every step and the structured `EscrowCreated` / `EscrowReleased`
//!    events asserted from the host event log.
//! 2. **Refund path**: create → timeout → (expire) → refund → close, with
//!    the structured `EscrowRefunded` event asserted and the sender made
//!    whole again.
//! 3. **Mutual exclusivity**: release and refund are guarded by the state
//!    machine and the same deadline clock, so a released escrow can never be
//!    refunded and a timed-out escrow can never be released. Refunding twice
//!    is refused by the state transition (double-spend protection), and the
//!    refund window exposes the same rule off-chain via `is_refundable`.
//!
//! The client wrappers generated by the Soroban SDK unwrap `Result`s
//! internally (panicking on error), so the refusal tests use `try_*` variants
//! and assert on the deterministic [`Error`] codes.

use astroid_escrow::{EscrowContract, EscrowContractClient, EscrowState};
use astroid_shared::events::ContractEvent;
use astroid_shared::types::AssetAmount;
use soroban_sdk::{
    testutils::{Address as _, Events as _, Ledger},
    token, vec, Address, Env, IntoVal, String, Vec,
};

const START: u64 = 1_000;
const GRACE: u64 = 1_000;
const AMOUNT: i128 = 10_000;

struct Harness<'a> {
    env: Env,
    escrow: EscrowContractClient<'a>,
    /// Recorded at `initialize` as the whitelist manager; kept so the harness
    /// mirrors the deployed wiring (escrow.approve_token runs with it).
    #[allow(dead_code)]
    admin: Address,
    sender: Address,
    recipient: Address,
    arbiter: Address,
    stranger: Address,
    asset: Address,
}

fn setup() -> Harness<'static> {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().with_mut(|l| l.timestamp = START);

    let admin = Address::generate(&env);
    let sender = Address::generate(&env);
    let recipient = Address::generate(&env);
    let arbiter = Address::generate(&env);
    let stranger = Address::generate(&env);

    let escrow_id = env.register_contract(None, EscrowContract);
    let escrow = EscrowContractClient::new(&env, &escrow_id);
    escrow.initialize(&admin);

    let token_admin = Address::generate(&env);
    let asset = env
        .register_stellar_asset_contract_v2(token_admin)
        .address();
    escrow.approve_token(&admin, &asset);

    token::StellarAssetClient::new(&env, &asset).mint(&sender, &AMOUNT);

    Harness {
        env,
        escrow,
        admin,
        sender,
        recipient,
        arbiter,
        stranger,
        asset,
    }
}

fn assets(h: &Harness) -> Vec<AssetAmount> {
    vec![
        &h.env,
        AssetAmount {
            asset: h.asset.clone(),
            amount: AMOUNT,
        },
    ]
}

fn create_escrow(h: &Harness, deadline: u64) -> u64 {
    h.escrow.create(
        &h.sender,
        &h.recipient,
        &h.arbiter,
        &assets(h),
        &deadline,
        &GRACE,
        &String::from_str(&h.env, "issue-292"),
        &Vec::new(&h.env),
        &0u32,
    )
}

fn balance(h: &Harness, who: &Address) -> i128 {
    token::TokenClient::new(&h.env, &h.asset).balance(who)
}

/// Move the ledger past `deadline + grace_period`, the instant at which the
/// arbiter's release path closes and the sender's refund paths open.
fn past_grace(h: &Harness, deadline: u64) {
    h.env.ledger().with_mut(|l| l.timestamp = deadline + GRACE);
}

/// Whether the host event log recorded a structured [`ContractEvent`]
/// (single topic equal to the variant symbol).
fn emitted(h: &Harness, event: &ContractEvent) -> bool {
    let topic: soroban_sdk::Val = match event {
        ContractEvent::EscrowCreated { .. } => {
            soroban_sdk::Symbol::new(&h.env, "EscrowCreated").into_val(&h.env)
        }
        ContractEvent::EscrowReleased { .. } => {
            soroban_sdk::Symbol::new(&h.env, "EscrowReleased").into_val(&h.env)
        }
        ContractEvent::EscrowRefunded { .. } => {
            soroban_sdk::Symbol::new(&h.env, "EscrowRefunded").into_val(&h.env)
        }
        _ => return false,
    };
    h.env
        .events()
        .all()
        .iter()
        .any(|(_id, topics, _data)| topics.contains(topic))
}

// ---------------------------------------------------------------------------
// Happy path: create → release → close
// ---------------------------------------------------------------------------

#[test]
fn escrow_release_lifecycle_moves_funds_to_recipient() {
    let h = setup();
    let deadline = START + 5_000;

    let id = create_escrow(&h, deadline);

    // Funds are in custody the moment `create` returns.
    assert_eq!(h.escrow.get(&id).state, EscrowState::Funded);
    assert_eq!(balance(&h, &h.escrow.address), AMOUNT);
    assert_eq!(balance(&h, &h.sender), 0);

    // Creation emits both the legacy tuple event and the structured one.
    assert!(emitted(
        &h,
        &ContractEvent::EscrowCreated {
            escrow_id: id,
            sender: h.sender.clone(),
            recipient: h.recipient.clone(),
            assets: assets(&h),
            deadline,
        }
    ));

    // Only the arbiter may release.
    let res = h.escrow.try_release(&h.stranger, &id, &AMOUNT);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::Unauthorized)));

    // Release inside the window pays the recipient in full.
    h.escrow.release(&h.arbiter, &id, &AMOUNT);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Released);
    assert_eq!(balance(&h, &h.recipient), AMOUNT);
    assert_eq!(balance(&h, &h.escrow.address), 0);
    assert!(emitted(
        &h,
        &ContractEvent::EscrowReleased {
            escrow_id: id,
            recipient: h.recipient.clone(),
            assets: assets(&h),
        }
    ));

    // A released escrow is terminal for value movement: close records it.
    h.escrow.close(&h.arbiter, &id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Closed);
}

// ---------------------------------------------------------------------------
// Refund path: create → timeout → refund → close
// ---------------------------------------------------------------------------

#[test]
fn escrow_expired_refund_returns_funds_to_depositor() {
    let h = setup();
    let deadline = START + 5_000;

    let id = create_escrow(&h, deadline);

    // Refund is refused while the escrow is live: before the deadline with
    // `TimeLockActive`, during the grace window with `GraceActive`.
    let res = h.escrow.try_refund(&h.sender, &id);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::TimeLockActive)));

    h.env.ledger().with_mut(|l| l.timestamp = deadline + 1);
    let res = h.escrow.try_refund(&h.sender, &id);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::GraceActive)));

    // A keeper flags the escrow expired once the grace has elapsed.
    past_grace(&h, deadline);
    h.escrow.expire(&id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Expired);
    // Expiry alone moves no value.
    assert_eq!(balance(&h, &h.escrow.address), AMOUNT);
    assert_eq!(balance(&h, &h.sender), 0);

    // Only the recorded sender may refund.
    let res = h.escrow.try_refund(&h.stranger, &id);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::Unauthorized)));

    // The refund returns the full custody balance to the depositor.
    h.escrow.refund(&h.sender, &id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Refunded);
    assert_eq!(balance(&h, &h.sender), AMOUNT);
    assert_eq!(balance(&h, &h.escrow.address), 0);
    assert!(emitted(
        &h,
        &ContractEvent::EscrowRefunded {
            escrow_id: id,
            sender: h.sender.clone(),
            assets: assets(&h),
        }
    ));

    h.escrow.close(&h.sender, &id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Closed);
}

/// The sender does not need a keeper: `reclaim` opens at the same instant as
/// `refund` and pulls the funds back without the `Expired` marker.
#[test]
fn escrow_reclaim_after_grace_needs_no_expired_marker() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    past_grace(&h, deadline);
    h.escrow.reclaim(&h.sender, &id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Refunded);
    assert_eq!(balance(&h, &h.sender), AMOUNT);
    assert_eq!(balance(&h, &h.escrow.address), 0);
    assert!(emitted(
        &h,
        &ContractEvent::EscrowRefunded {
            escrow_id: id,
            sender: h.sender.clone(),
            assets: assets(&h),
        }
    ));
}

/// `is_refundable` mirrors the on-chain rule so clients need not recompute
/// it: false while the escrow is live, true once the grace has elapsed, and
/// false again once the funds have been returned.
#[test]
fn is_refundable_tracks_the_refund_window() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    assert!(!h.escrow.is_refundable(&id));
    past_grace(&h, deadline);
    assert!(h.escrow.is_refundable(&id));

    h.escrow.reclaim(&h.sender, &id);
    assert!(!h.escrow.is_refundable(&id));
}

// ---------------------------------------------------------------------------
// Mutual exclusivity of the release and refund paths
// ---------------------------------------------------------------------------

/// A released escrow can never be refunded — the funds are gone and the state
/// transition refuses the second settlement.
#[test]
fn released_escrow_is_excluded_from_refund() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    h.escrow.release(&h.arbiter, &id, &AMOUNT);
    past_grace(&h, deadline);

    let res = h.escrow.try_refund(&h.sender, &id);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::InvalidState)));
    assert_eq!(h.escrow.get(&id).state, EscrowState::Released);
    assert_eq!(balance(&h, &h.sender), 0);
    assert_eq!(balance(&h, &h.recipient), AMOUNT);
}

/// A timed-out escrow can never be released — the deadline condition is
/// verified on the release attempt itself, marker or no marker, so the
/// arbiter cannot pay the recipient out of escrow the depositor is
/// entitled to reclaim.
#[test]
fn expired_escrow_is_excluded_from_release() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    // Unmarked but past the window: the release condition is verified against
    // the deadline on the attempt, not just against the stored marker.
    past_grace(&h, deadline);
    let res = h.escrow.try_release(&h.arbiter, &id, &AMOUNT);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::EscrowExpired)));
    assert_eq!(h.escrow.get(&id).state, EscrowState::Funded);
    assert_eq!(balance(&h, &h.escrow.address), AMOUNT);

    // Explicitly marked: same refusal.
    h.escrow.expire(&id);
    let res = h.escrow.try_release(&h.arbiter, &id, &AMOUNT);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::InvalidState)));
    assert_eq!(balance(&h, &h.escrow.address), AMOUNT);
    assert_eq!(balance(&h, &h.recipient), 0);
}

/// A refund consumes the escrow: a second refund attempt is refused by the
/// state machine, so custody can never be paid out twice.
#[test]
fn refund_cannot_be_executed_twice() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    past_grace(&h, deadline);
    h.escrow.reclaim(&h.sender, &id);
    assert_eq!(balance(&h, &h.sender), AMOUNT);

    let res = h.escrow.try_refund(&h.sender, &id);
    assert_eq!(res, Err(Ok(astroid_shared::errors::Error::InvalidState)));
    assert_eq!(h.escrow.get(&id).state, EscrowState::Refunded);
    assert_eq!(balance(&h, &h.sender), AMOUNT);
    assert_eq!(balance(&h, &h.escrow.address), 0);
}

/// A keeper-flagged expiry never locks the depositor out: the `Expired`
/// state is a marker only, and refund still pays out in full afterwards.
#[test]
fn expired_marker_never_strands_funds() {
    let h = setup();
    let deadline = START + 5_000;
    let id = create_escrow(&h, deadline);

    past_grace(&h, deadline);
    h.escrow.expire(&id);

    h.escrow.refund(&h.sender, &id);
    assert_eq!(h.escrow.get(&id).state, EscrowState::Refunded);
    assert_eq!(balance(&h, &h.sender), AMOUNT);
    assert_eq!(balance(&h, &h.escrow.address), 0);
}
